# This file was generated by GoReleaser. DO NOT EDIT.
cask "igit" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "igit"], chdir: "."
    end
  end

  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "eeffe6db6e1487bd7faa4a79012dfaccad48c0f69c84566ff30c8687527f17da"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e1094a7faf4126a4fcfac67d98c60732350ac89fea7271e72d08c29f1717c0c"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5be076c964458c2b34610102b84ea17a66722d06b55598ff4a140cc9405c8bdc"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b887ae27f2cc0d44271da0d750ce5fd541b46cd563390086675767c6a8aedf52"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "igit"
  desc "Review and GIT tools"
  homepage "https://github.com/yousysadmin/igit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "igit"

  # No zap stanza required
end
