# This file was generated by GoReleaser. DO NOT EDIT.
cask "igit" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "igit"], chdir: "."
    end
  end

  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "de7f2193428818a484b49588da35fbeb10e5ed8d52054628a29d2451b4d483bc"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e4383b9b2f433f6ed1a6233fbee4f269bf5f1238ac3e20d26ca2e1c920cbb770"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2743d71393e3b56a767cbf9e4851d62038ba1d4299e1c3434bb0020cc5814ca2"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5c03f2cfc65a631cd6dd4c897f2da181d06b2f422c91b89e06b5e7322d90868"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "igit"
  desc "Review and GIT tools"
  homepage "https://github.com/yousysadmin/igit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "igit"

  # No zap stanza required
end
