# This file was generated by GoReleaser. DO NOT EDIT.
cask "igit" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "eba3deceaf943d3418acf7e4023b92a1a7b123e8ea9c8481c0f8b51017987403"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b0362f02b8dba087088ea0c8cd1eadb15088a7ae0676728651b3db6229d5d95"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a945e2196c9ac82e013751d00c758d0e179368add4ef2e016d0337f2361f1853"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc179d3cbc219d3b2dbccabaa70e47d10f0a033b3c90e863e51c1cedacda78f8"
      url "https://github.com/YouSysAdmin/igit/releases/download/v#{version}/igit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "igit"
  desc "Review and GIT tools"
  homepage "https://github.com/yousysadmin/igit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "igit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/igit"]
    end
  end

  # No zap stanza required
end
