# This file was generated by GoReleaser. DO NOT EDIT.
cask "ihttp" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "04c3637ac3f9f241a58c379d0bebba133d16379b1ed1439bed1310cbfac381aa"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1604d4ee7183be5bdcc8376e03a4bd619415f073ca9e8300a74be70178992485"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d2771de70b2418554cf392127b48ffa9d3fbbcac4ce4f879bb4d61f73e3ddbb2"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9015b4f827abb90bb1a527fdbc12d0a815def95fb2ed3ba59bfe992779ab07d9"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "ihttp"
  desc "HTTP toolkit for security research"
  homepage "https://github.com/yousysadmin/ihttp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ihttp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ihttp"]
    end
  end

  # No zap stanza required
end
