# This file was generated by GoReleaser. DO NOT EDIT.
cask "ihttp" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "09bb0714d5256e929188827973be514f3c8d9a5c27e5e1733270812a263efbad"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1288f170c57f5778df8404735f8a0da5794593f547827a2e5f694744fde0fa6"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "457407fdc28050ffaaa91db068b238966ba0c6ef45801c8d417082c4b28c6049"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bad4ff09d477fff9bcf35854cebda331196a83974f076076a3e822a97b971e14"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "ihttp"
  desc "HTTP toolkit for security research"
  homepage "https://github.com/yousysadmin/ihttp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ihttp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ihttp"]
    end
  end

  # No zap stanza required
end
