# This file was generated by GoReleaser. DO NOT EDIT.
cask "ihttp" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "c3b5055abac21b6f4df94eb5696666468967fda779dded75097372a5eb796b70"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "87f65a62b666091820f8075c1761d5064dbc1f41a6501cee329087e15bd63f1d"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3caa794ac8f10f05c9a63aeb26c2afdc4ca191209dfb53ff22ec7f4c6baa75f3"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "829cfd5f3313d9ca1eed989fff3b959e4b4ca6cb60326cd5c6511699a23efd58"
      url "https://github.com/yousysadmin/ihttp/releases/download/v#{version}/ihttp_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "ihttp"
  desc "HTTP toolkit for security research"
  homepage "https://github.com/yousysadmin/ihttp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ihttp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ihttp"]
    end
  end

  # No zap stanza required
end
