# This file was generated by GoReleaser. DO NOT EDIT.
cask "lmnt" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "e6bb1aeb01dea558c8da91e78d877cce41000559fde4053c1fad36d1b5d2234d"
      url "https://github.com/YouSysAdmin/lmnt/releases/download/v#{version}/lmnt_v#{version}_darwin_arm64.tar.gz"
    end
  end

  name "lmnt"
  desc "Mount Linux-native disks (ext4, xfs, btrfs, LVM, LUKS) on macOS"
  homepage "https://github.com/yousysadmin/lmnt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lmnt"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lmnt"]
    end
  end

  # No zap stanza required
end
