# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlatSpf < Formula
  desc "The tool that flattens records"
  homepage "https://github.com/yousysadmin/flat-spf"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YouSysAdmin/flat-spf/releases/download/v0.1.0/flat-spf_v0.1.0_darwin_amd64.tar.gz"
      sha256 "326c859d53fb8fd48a61f4adc9448ac4137f7ed6a3a4f423a4c70dbad3b0f559"

      define_method(:install) do
        bin.install "flat-spf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/flat-spf/releases/download/v0.1.0/flat-spf_v0.1.0_darwin_arm64.tar.gz"
      sha256 "229d042696f2780a27f46777be3e7b5b8f20e1f7f06fe08c4bfa17c917819cf9"

      define_method(:install) do
        bin.install "flat-spf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/flat-spf/releases/download/v0.1.0/flat-spf_v0.1.0_linux_amd64.tar.gz"
      sha256 "6dcdd12a27082551fa75ea2a51a47341d66611e2aa92cc80e570094e63f18eb6"
      define_method(:install) do
        bin.install "flat-spf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/flat-spf/releases/download/v0.1.0/flat-spf_v0.1.0_linux_arm64.tar.gz"
      sha256 "469c33d1d7fbf792cdd0a979732de9da2ce3a4b65da947d6c00a33d1d68b7b91"
      define_method(:install) do
        bin.install "flat-spf"
      end
    end
  end
end
