# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeadscalePf < Formula
  desc "Obtaining information about groups and group members from external sources and populating groups in the Headscale policy"
  homepage "https://github.com/yousysadmin/headscale-pf"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YouSysAdmin/headscale-pf/releases/download/v2.4.0/headscale-pf_v2.4.0_darwin_amd64.tar.gz"
      sha256 "84f61dad4658da8ac6efe029476dce593c4e9159052b6bac63f83fe89456034f"

      define_method(:install) do
        bin.install "headscale-pf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/headscale-pf/releases/download/v2.4.0/headscale-pf_v2.4.0_darwin_arm64.tar.gz"
      sha256 "846a5cc5ffd7a0da5cb8fe1c7ecc29e62c64967225b45d7f0e19cb8148109af4"

      define_method(:install) do
        bin.install "headscale-pf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/headscale-pf/releases/download/v2.4.0/headscale-pf_v2.4.0_linux_amd64.tar.gz"
      sha256 "d0eaf0329921c4b16a784bf5c37289d780c1d57369287093363f0ebc66a01d50"
      define_method(:install) do
        bin.install "headscale-pf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/headscale-pf/releases/download/v2.4.0/headscale-pf_v2.4.0_linux_arm64.tar.gz"
      sha256 "df2142f160239b24b0427da1ac59cd526592c53019c66cde4acec240a5d73839"
      define_method(:install) do
        bin.install "headscale-pf"
      end
    end
  end
end
