# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeadscalePf < Formula
  desc "Obtaining information about groups and group members from external sources and populating groups in the Headscale policy"
  homepage "https://github.com/yousysadmin/headscale-pf"
  version "2.4.0-pre"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YouSysAdmin/headscale-pf/releases/download/v2.4.0-pre/headscale-pf_v2.4.0-pre_darwin_amd64.tar.gz"
      sha256 "bad8cadcb352cc271e52249ec8e1645a3c3288cdc589cdebd1d1fcdf6b9eb8c3"

      define_method(:install) do
        bin.install "headscale-pf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/headscale-pf/releases/download/v2.4.0-pre/headscale-pf_v2.4.0-pre_darwin_arm64.tar.gz"
      sha256 "613147db92949b7c0497204f511fc32e18ddbdc8a6998ef3156b6dd9dc61a3d4"

      define_method(:install) do
        bin.install "headscale-pf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/headscale-pf/releases/download/v2.4.0-pre/headscale-pf_v2.4.0-pre_linux_amd64.tar.gz"
      sha256 "a09d04183784099622630cebd690afa0f044b958ad84713721eceacadd24bf8f"
      define_method(:install) do
        bin.install "headscale-pf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/headscale-pf/releases/download/v2.4.0-pre/headscale-pf_v2.4.0-pre_linux_arm64.tar.gz"
      sha256 "d0b1efa8974d8261b3126f0f426cb4bf4bece194a982b49cf98a439708657dbc"
      define_method(:install) do
        bin.install "headscale-pf"
      end
    end
  end
end
