# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Igit < Formula
  desc "Review and GIT tools"
  homepage "https://github.com/yousysadmin/igit"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YouSysAdmin/igit/releases/download/v1.0.0/igit_1.0.0_darwin_amd64.tar.gz"
      sha256 "b77ea0b5bf989a4b12cc999bf019ed22d622fd1061f3c46abdb8f2739063c52e"

      define_method(:install) do
        bin.install "igit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/igit/releases/download/v1.0.0/igit_1.0.0_darwin_arm64.tar.gz"
      sha256 "9be58c0d9e51f07c245ea0c7fbd3ae0a1314df520078445d91531fab1d4dc743"

      define_method(:install) do
        bin.install "igit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/igit/releases/download/v1.0.0/igit_1.0.0_linux_amd64.tar.gz"
      sha256 "0bc978e35a993df0641c2aa3738261e258335b34855ba02cfa8f8dc61a53196e"
      define_method(:install) do
        bin.install "igit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/igit/releases/download/v1.0.0/igit_1.0.0_linux_arm64.tar.gz"
      sha256 "11bbcbd125722a143b3d60e8c001f3824ce5024302f2c25d4806342b5e10d7ab"
      define_method(:install) do
        bin.install "igit"
      end
    end
  end
end
