# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Igit < Formula
  desc "Review and GIT tools"
  homepage "https://github.com/yousysadmin/igit"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YouSysAdmin/igit/releases/download/v1.2.1/igit_1.2.1_darwin_amd64.tar.gz"
      sha256 "57f65dff7fa1adf4e954545d3051bed01ad6a3336458a7399c3153482bcbdd3d"

      define_method(:install) do
        bin.install "igit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/igit/releases/download/v1.2.1/igit_1.2.1_darwin_arm64.tar.gz"
      sha256 "832a0a23a5313f4e8d50fcf5e4bc2f1b1afd3c07d0725ca4954b7d8a16cf5701"

      define_method(:install) do
        bin.install "igit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/igit/releases/download/v1.2.1/igit_1.2.1_linux_amd64.tar.gz"
      sha256 "5f1ac780ae938f5b116d67ac8e35e8f13a76d1e5099500973965a698b599e10a"
      define_method(:install) do
        bin.install "igit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/igit/releases/download/v1.2.1/igit_1.2.1_linux_arm64.tar.gz"
      sha256 "ef8da8c5389efacb5681631373fd51c92387062bbc3cc460d83faac7462385e0"
      define_method(:install) do
        bin.install "igit"
      end
    end
  end
end
