# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jc2aws < Formula
  desc "Get AWS credentials via Jumpcloud SAML"
  homepage "https://github.com/umputun/revdiff"
  version "4.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YouSysAdmin/jc2aws/releases/download/v4.1.0/jc2aws_v4.1.0_darwin_amd64.tar.gz"
      sha256 "5b8d42f1ebf042a2c5a41cfb4b5b18848a5d7679dfb1346281598228921f654c"

      define_method(:install) do
        bin.install "jc2aws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/jc2aws/releases/download/v4.1.0/jc2aws_v4.1.0_darwin_arm64.tar.gz"
      sha256 "7c087e773953631211a1ce1c47a5f0f99a75f69cbbad5fdcc32c19e66a10a6d3"

      define_method(:install) do
        bin.install "jc2aws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/jc2aws/releases/download/v4.1.0/jc2aws_v4.1.0_linux_amd64.tar.gz"
      sha256 "9d5502870544e25ae06006206bdf260db6bd74a30732762f1c0c3d4fc4ab6a24"
      define_method(:install) do
        bin.install "jc2aws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/jc2aws/releases/download/v4.1.0/jc2aws_v4.1.0_linux_arm64.tar.gz"
      sha256 "3028cab275b43f24c507a631ee53e77fb99a11b635fedc41677e98f7f71bffdd"
      define_method(:install) do
        bin.install "jc2aws"
      end
    end
  end
end
