# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jc2aws < Formula
  desc "Get AWS credentials via Jumpcloud SAML"
  homepage "https://github.com/yousysadmin/jc2aws"
  version "4.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YouSysAdmin/jc2aws/releases/download/v4.2.0/jc2aws_v4.2.0_darwin_amd64.tar.gz"
      sha256 "d1be7f868cdd532fcb345f2e64693c00890b8479e376af8fd1a20ea81bed5a1e"

      define_method(:install) do
        bin.install "jc2aws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/jc2aws/releases/download/v4.2.0/jc2aws_v4.2.0_darwin_arm64.tar.gz"
      sha256 "10569da7d229f66d48c926a9f9b3ef54ffef023f487a831ec7485069208aae05"

      define_method(:install) do
        bin.install "jc2aws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/jc2aws/releases/download/v4.2.0/jc2aws_v4.2.0_linux_amd64.tar.gz"
      sha256 "d20f3c91eada52694c5cc2b3709c87effff876097d995f49154ecca6262579b0"
      define_method(:install) do
        bin.install "jc2aws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/jc2aws/releases/download/v4.2.0/jc2aws_v4.2.0_linux_arm64.tar.gz"
      sha256 "168aa1b25e2957ca5985dcd19cf7e3681b3307c3ec9538c82ac809e9ffb5b220"
      define_method(:install) do
        bin.install "jc2aws"
      end
    end
  end
end
