# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kv < Formula
  desc "KV is a secure and lightweight command-line key-value store built in Go."
  homepage "https://github.com/yousysadmin/kv"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YouSysAdmin/kv/releases/download/v2.4.0/kv_v2.4.0_darwin_amd64.tar.gz"
      sha256 "d3d5d317047180be3a3679b4760a1912e6c96c010c481be14fe1d5a93238b07d"

      define_method(:install) do
        bin.install "kv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/kv/releases/download/v2.4.0/kv_v2.4.0_darwin_arm64.tar.gz"
      sha256 "9f4da3ddde89683e2bd4a790cedcb1897cb53c13bfcbe45ab6b15958615a58e0"

      define_method(:install) do
        bin.install "kv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/kv/releases/download/v2.4.0/kv_v2.4.0_linux_amd64.tar.gz"
      sha256 "eec40a2dddaf38fc688af74d3558ee43a1142760ab571c18d1f89396c0cb3020"
      define_method(:install) do
        bin.install "kv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/kv/releases/download/v2.4.0/kv_v2.4.0_linux_arm64.tar.gz"
      sha256 "da477b6eccd34a4bdecb45d7e33da2237375a8181816897c002a8286c0ae63f6"
      define_method(:install) do
        bin.install "kv"
      end
    end
  end
end
