# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttt < Formula
  desc "Task & Time Tracking tool"
  homepage "https://github.com/YouSysAdmin/ttt"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/ttt/releases/download/v0.1.0/ttt_v0.1.0_darwin_arm64.tar.gz"
      sha256 "7b15defc63ee279bd5db27ea3c983f592e685b15bf3e39dc39f13562c8682afb"

      define_method(:install) do
        bin.install "ttt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/ttt/releases/download/v0.1.0/ttt_v0.1.0_linux_amd64.tar.gz"
      sha256 "8302b8df5d9294b66f91994b6d454a1dc7bd41f70c49558d1a12b4ac8463449e"
      define_method(:install) do
        bin.install "ttt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/ttt/releases/download/v0.1.0/ttt_v0.1.0_linux_arm64.tar.gz"
      sha256 "63bce1aa55a0cdfedd48cec2980e520edd2e37b4a125d6c736c15673f7e53f1b"
      define_method(:install) do
        bin.install "ttt"
      end
    end
  end
end
