# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whoosh < Formula
  desc "A single-binary deployment tool"
  homepage "https://github.com/YouSysAdmin/whoosh"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.6.0/whoosh_v1.6.0_darwin_arm64.tar.gz"
      sha256 "8fb841609d16ce9897c9042dc444a562029f7c4063268dff0c1098b2bc9ec867"

      define_method(:install) do
        bin.install "whoosh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.6.0/whoosh_v1.6.0_linux_amd64.tar.gz"
      sha256 "aef05716b27ee5c06bea0f141f4da50746b8d17086a1c566d895cd08568afc59"
      define_method(:install) do
        bin.install "whoosh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.6.0/whoosh_v1.6.0_linux_arm64.tar.gz"
      sha256 "7b685b561f4120c16c1825583ef05e3b238081c47605b2901d21ea8f2d0ce807"
      define_method(:install) do
        bin.install "whoosh"
      end
    end
  end
end
