# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whoosh < Formula
  desc "A single-binary deployment tool"
  homepage "https://github.com/YouSysAdmin/whoosh"
  version "1.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.8.1/whoosh_v1.8.1_darwin_arm64.tar.gz"
      sha256 "2ea5173a13a6f8692408ed89af8d49b9349ada850ef56560a31ecfad62d89bbd"

      define_method(:install) do
        bin.install "whoosh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.8.1/whoosh_v1.8.1_linux_amd64.tar.gz"
      sha256 "d4d8c76ae07f1e342d591ef2201592e38cec7e31153e0585d51ded85232ee4b6"
      define_method(:install) do
        bin.install "whoosh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.8.1/whoosh_v1.8.1_linux_arm64.tar.gz"
      sha256 "90304c63a6e81fcbe008e1d6109b91e3f5c4b1ff5fed0a819548e6aa29095292"
      define_method(:install) do
        bin.install "whoosh"
      end
    end
  end
end
