# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whoosh < Formula
  desc "A single-binary deployment tool"
  homepage "https://github.com/YouSysAdmin/whoosh"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.8.0/whoosh_v1.8.0_darwin_arm64.tar.gz"
      sha256 "39d992bd3cdfc8c428ea3a08d660e96c7128b7c8af3e3d0535166a509f60cdab"

      define_method(:install) do
        bin.install "whoosh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.8.0/whoosh_v1.8.0_linux_amd64.tar.gz"
      sha256 "2cade95ff409d8f355e7c8032d9aa8d5d562b876c1cbd552a630e4911dfcbf5b"
      define_method(:install) do
        bin.install "whoosh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YouSysAdmin/whoosh/releases/download/v1.8.0/whoosh_v1.8.0_linux_arm64.tar.gz"
      sha256 "88fbe38a2df37753ed588f0556a8891ab9eaaa0fdf1f41c9d526e6fc38300333"
      define_method(:install) do
        bin.install "whoosh"
      end
    end
  end
end
